### ISSUE TITLE
Refactor CI github actions to multiple jobs instead one job

### ISSUE THREAD

**Issue by davidnguyen179** [davidnguyen179/web-extension-boilerplate#19]

**Comment by davidnguyen179** [comment]
sample script 

```yml
name: spotify extension ci/cd
on:
  push:
jobs:
  installation:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7.12.2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
      run: pnpm install --frozen-lockfile
  linter:
    runs-on: ubuntu-20.04
    needs: [installation]
    concurrency: validation-${{ github.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7.12.2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
      run: pnpm install --frozen-lockfile
    - name: Running typecheck... 🩺 🔬 🔭
      run: pnpm code:typecheck
    - name: Running eslint... 👀
      run: pnpm code:lint
  test:
    runs-on: ubuntu-20.04
    needs: [installation]
    concurrency: validation-${{ github.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7.12.2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
      run: pnpm install --frozen-lockfile
    - name: Running unit test... 🤞 🚑 💊
      run: pnpm test:unit --runInBand --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
  build:
    runs-on: ubuntu-20.04
    needs: [installation, linter, test]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7.12.2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
      run: pnpm install --frozen-lockfile
    - name: Run build Chrome
      run: pnpm app:chrome
    - name: Run build Firefox
      run: pnpm app:firefox
    - name: Run build Edge
      run: pnpm app:edge
```
